### ISSUE TITLE
运行项目报错

### ISSUE THREAD

**Issue by azui007** [Romanluo1990/flink-mybatis-demo#2]
java.lang.NoClassDefFoundError: Could not initialize class roman.flink.mybatis.ApplicationContextManager$InjectorHolder
	at roman.flink.mybatis.ApplicationContextManager.getApplicationContext(ApplicationContextManager.java:22) ~[classes/:na]
	at roman.flink.mybatis.ApplicationContextManager.getInstance(ApplicationContextManager.java:26) ~[classes/:na]
	at roman.flink.mybatis.flink.UserInfoSaveSink.open(UserInfoSaveSink.java:20) ~[classes/:na]
	at org.apache.flink.api.common.functions.util.FunctionUtils.openFunction(FunctionUtils.java:36) ~[flink-core-1.8.0.jar:1.8.0]
	at org.apache.flink.streaming.api.operators.AbstractUdfStreamOperator.open(AbstractUdfStreamOperator.java:102) ~[flink-streaming-java_2.11-1.8.0.jar:1.8.0]
	at org.apache.flink.streaming.api.operators.StreamSink.open(StreamSink.java:48) ~[flink-streaming-java_2.11-1.8.0.jar:1.8.0]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.openAllOperators(StreamTask.java:424) ~[flink-streaming-java_2.11-1.8.0.jar:1.8.0]
	at org.apache.flink.streaming.runtime.tasks.StreamTask.invoke(StreamTask.java:290) ~[flink-streaming-java_2.11-1.8.0.jar:1.8.0]
	at org.apache.flink.runtime.taskmanager.Task.run(Task.java:711) ~[flink-runtime_2.11-1.8.0.jar:1.8.0]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
2021-08-25 10:24:12.656 INFO  org.apache.flink.runtime.taskmanager.Task Line:810 - Freeing task resources for Map -> (Sink: Print to Std. Out, Sink: Unnamed) (2/4) (6d707c26513b86c225471f4fb1cc220e).

**Comment by azui007** [comment]
修改依赖版本解决
